name: e_wallet_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.3
  google_fonts: 6.1.0
  flutter_gen: ^5.7.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.2

  vector_graphics: any
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
